# Generated by Django 3.1.6 on 2021-02-18 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210218_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 18, 17, 2, 25, 131431)),
            preserve_default=False,
        ),
    ]
