# Generated by Django 3.1.6 on 2021-02-03 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210203_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='Post_Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7, verbose_name='Post Privacy'),
        ),
    ]
