# Generated by Django 3.1.6 on 2021-02-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=150, verbose_name='Comment'),
        ),
    ]
