# Generated by Django 3.1.6 on 2021-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210203_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='Post_Images/default.png', null=True, upload_to='User_Images'),
        ),
    ]
