# Generated by Django 3.1.6 on 2021-02-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='User_Images/default.png', null=True, upload_to='User_Images'),
        ),
    ]
