# Generated by Django 3.1.6 on 2021-02-11 06:57

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='NZ', max_length=2),
            preserve_default=False,
        ),
    ]
